### ISSUE TITLE
Add/link openHistorian to openMIC

### ISSUE THREAD

**Issue by RobertZomborszki** [GridProtectionAlliance/openMIC#7]
Hi,

I've just started to use openHistorian and openMIC, but I was unable to connect them. I have an openMIC installed on my machine that reads Modbus data. And I have an openHistorian installed on the same machine connected to Grafana. But I was unable to connect the measurement in openMIC to openHistorian. How can I do this? I'm pretty sure it is possible I just have to learn the nomenclature.

Thank you for your help in advance.
Robert

**Comment by ritchiecarroll** [comment]
You need to create an internal subscription from the openHistorian to openMIC. To do this, from the openHistorian Manager (i.e., the GUI app from start menu not the Web UI), go to “Inputs > Subscription Based Inputs > Create Internal Subscription” from the main menu.

On this screen enter “Acronym = MIC, Name = MIC, Hostname = localhost, Port = 6195” - also make sure that *both* receive internal and external metadata checkboxes are selected, then click Next. 

From the next screen verify that the “Historian” drop down is set to “PPA” (or your primary archive instance) and make sure “Enabled” is checked and click “Save” – this should establish a connection to the openMIC and start archiving all data.

At this point you should be able to get points into Grafana and see data in the openHistorian web UI...

Thanks,
Ritchie

**Comment by RobertZomborszki** [comment]
Thank you Ritchie. It was really easy and now it is working. Thank you again for your help
