### ISSUE TITLE
SQL logic error - no such table: StatusLog

### ISSUE THREAD

**Issue by pdb5627** [GridProtectionAlliance/openMIC#8]
I performed a fresh install of openMIC this morning (App Version 1.0.107) set to use an SQLite DB. I configured it to connect to a test relay in our lab, and it looks like it does succeed in making the FTP connection and listing the directory contents, but it fails to retrieve any data. I see the following messages in the console log:
```
[LAB351] Enumerating remote files in "/EVENTS"...

[LAB351] Found 117 remote files, starting file processing...

[LAB351] Failed to update StatusLog database for device "LAB351": Exception during record 
query for StatusLog "SELECT ID FROM StatusLog WHERE DeviceID = {0} ORDER BY ID, 
0:System.Data.SQLite.SQLiteParameter": SQL logic error or missing database
no such table: StatusLog

[LAB351] FTP session connected for 4.01 seconds
```

In the SQLite database creation SQL commands, I see that there is a section that looks like it is supposed to create the StatusLog table:
```
CREATE TABLE [dbo].[StatusLog](		
      [ID] [int] IDENTITY(1,1) NOT NULL,		
      [DeviceID] [int] NOT NULL,		
      [LastSuccess] [DateTime2] NULL,		
	  [LastFailure] [DateTime2] NULL,		
      [Message] [varchar](max) NULL,
	  [LastFile] [varchar](max) NULL		
);
```

When I manually try to run those commands in a DB Browser for SQLite, it gives unknown database and syntax errors. Possibly those commands need to be translated for SQLite and the distributed SQLite openMIC.db file rebuilt accordingly?

**Comment by ritchiecarroll** [comment]
I think this got skipped in the schema update... @wbernest

**Comment by ritchiecarroll** [comment]
This commit should fix: 413781a71313e2d41e502c5f1aaea01d4eb6c384

**Comment by ritchiecarroll** [comment]
I am testing now - if it works, I run a new build...

**Comment by ritchiecarroll** [comment]
Looks like it's working for me - I will run a new build.

**Comment by ritchiecarroll** [comment]
Fixed here: https://github.com/GridProtectionAlliance/openMIC/releases/tag/v1.1
